import HomeLayout from "@/components/homeLayout/HomeLayout";
import "./globals.css";
import { SidebarProvider } from "../context/sidebar-context";
import "react-datetime/css/react-datetime.css";
import "react-loading-skeleton/dist/skeleton.css";
import Providers from "./Providers";
import { GoogleOAuthProvider } from "@react-oauth/google";
export const metadata = {
  title: "Ticketing",
  description: "Generated by create next app",
};

const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <GoogleOAuthProvider clientId={GOOGLE_CLIENT_ID}>
          <SidebarProvider>
            <div>
              {/* Sidebar and content layout */}
              <HomeLayout>
                <Providers>{children}</Providers>
              </HomeLayout>
            </div>
          </SidebarProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
