import HomeLayout from "@/components/homeLayout/HomeLayout";
import "./globals.css";
import { SidebarProvider } from "../context/sidebar-context";

export const metadata = {
  title: "Ticketing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <SidebarProvider>
          <div>
            {/* Sidebar and content layout */}
            <HomeLayout>{children}</HomeLayout>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
